name: Update translation progress

on:
  workflow_dispatch:

  schedule:
    - cron: "17 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Update Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_MESSAGE_ID: ${{ vars.DISCORD_MESSAGE_ID }}
        run: python progress.py
